00:15 1st October 2014

Today I worked on my long waiting PR https://github.com/sympy/sympy/pull/7523/commits.
It is almost ready to merge but there was a travis error in the last commit.
And the error was only in two Jobs one of Python 2.7 and other of Python 3.4 It
was in a slow marked test named `test_quintics_1`. Since it was a slow test
I had to wait a lot of time to manually run the test, and the error on my
machine was Maximum Recurssion Depth and on the online Travis build it was
`TypeError: Propositional logic <something>`. The error was in calculating if
the very big and complicated expression produced by solver is real or not.
I didn't care much about the very big and complicated expression and honestly
I wanted to drop that particular test. After sometime I found out that the
particular test was duplicated. There was another function `test_quintics`
which tested for the same equation in the same manner and it had another
equation. I removed the duplicated `test_quintics_1` and we were good to go.
Maybe someday I'll investigate the "real" reason for the test failure. For the
time being I want to get the PR merged.
